name: "snyk code test"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
